hyperparams:
  beta2_exp: 0.9907519748343652
  beta3_exp: 0.9983190052289349
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    kKGFMPU58j8=
  num_mixtures: 169
  rand_sphere_size: 100.26271027908972
optimization:
  batch_size: 1772
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    2vh9FR4Eaj8=
  lr_decay_max_drops: 15
  lr_decay_p_thresh: 0.6610348651345002
  lr_decay_p_window: 9
  lr_decay_slope_less: -0.0016725639156536225
  lr_decay_window: 43
  num_epochs: 11
  opt_shape_scale: 3.2739259152104507
random_seed: 42
rendering:
  image_height: 215
  image_width: 242
  num_views: 26
  vfov_degrees: 54.54250078440621
