hyperparams:
  beta2_exp: 4.814161697141419
  beta3_exp: 0.1670007559645583
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    T7F0h39P2j8=
  num_mixtures: 91
  rand_sphere_size: 178.4190095554039
optimization:
  batch_size: 1122
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    6PNDgyhCWT8=
  lr_decay_max_drops: 18
  lr_decay_p_thresh: 0.7173470814095158
  lr_decay_p_window: 9
  lr_decay_slope_less: -0.0053390762052568826
  lr_decay_window: 19
  num_epochs: 15
  opt_shape_scale: 4.635566591539508
random_seed: 42
rendering:
  image_height: 201
  image_width: 215
  num_views: 44
  vfov_degrees: 24.99207865094646
