hyperparams:
  beta2_exp: 3.088141041486545
  beta3_exp: 0.46125522743355146
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    cARmvXzKwD8=
  num_mixtures: 195
  rand_sphere_size: 98.05140257842956
optimization:
  batch_size: 2305
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    16Pp38aAdj8=
  lr_decay_max_drops: 11
  lr_decay_p_thresh: 0.6441868339608366
  lr_decay_p_window: 6
  lr_decay_slope_less: -0.007972484658002753
  lr_decay_window: 26
  num_epochs: 92
  opt_shape_scale: 4.822325578198253
random_seed: 42
rendering:
  image_height: 228
  image_width: 249
  num_views: 25
  vfov_degrees: 59.2854467159995
