hyperparams:
  beta2_exp: 2.424617989874437
  beta3_exp: 0.9539544549875217
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    HCiz6lSKB0A=
  num_mixtures: 54
  rand_sphere_size: 182.27736697712038
optimization:
  batch_size: 332
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    y1JaxNu0yz8=
  lr_decay_max_drops: 25
  lr_decay_p_thresh: 0.6200697608057868
  lr_decay_p_window: 7
  lr_decay_slope_less: -0.0074716222054803305
  lr_decay_window: 25
  num_epochs: 97
  opt_shape_scale: 1.402210310313042
random_seed: 42
rendering:
  image_height: 253
  image_width: 113
  num_views: 8
  vfov_degrees: 53.856682742746905
