hyperparams:
  beta2_exp: 2.4889016204276952
  beta3_exp: 0.1446597446696476
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    kABbcW3T1j8=
  num_mixtures: 181
  rand_sphere_size: 103.55153456430803
optimization:
  batch_size: 3160
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    dL9SbSjv7D8=
  lr_decay_max_drops: 7
  lr_decay_p_thresh: 0.6621037090767373
  lr_decay_p_window: 4
  lr_decay_slope_less: -0.008606149328258752
  lr_decay_window: 41
  num_epochs: 44
  opt_shape_scale: 1.9923682745078364
random_seed: 42
rendering:
  image_height: 207
  image_width: 147
  num_views: 35
  vfov_degrees: 21.765443735058756
