hyperparams:
  beta2_exp: 3.1504670977091065
  beta3_exp: 0.9350276474801192
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    KtOwrvWYzT8=
  num_mixtures: 183
  rand_sphere_size: 187.72702228797812
optimization:
  batch_size: 1994
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    fWtgTVju5T8=
  lr_decay_max_drops: 30
  lr_decay_p_thresh: 0.846250462718448
  lr_decay_p_window: 13
  lr_decay_slope_less: -0.0018752523434982672
  lr_decay_window: 14
  num_epochs: 40
  opt_shape_scale: 1.0982604286073632
random_seed: 42
rendering:
  image_height: 254
  image_width: 143
  num_views: 10
  vfov_degrees: 36.48889843725999
