hyperparams:
  beta2_exp: 2.226314962743686
  beta3_exp: 0.9929038774362412
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    GeUm0kx4vj8=
  num_mixtures: 33
  rand_sphere_size: 148.67879921674427
optimization:
  batch_size: 2263
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    1rtj49axtT8=
  lr_decay_max_drops: 15
  lr_decay_p_thresh: 0.46679575650916816
  lr_decay_p_window: 3
  lr_decay_slope_less: -0.007326822281848383
  lr_decay_window: 35
  num_epochs: 62
  opt_shape_scale: 2.1301693386696727
random_seed: 42
rendering:
  image_height: 150
  image_width: 188
  num_views: 46
  vfov_degrees: 41.010498166397106
