[workspace]
name = "fuzzy-metaballs"
version = "0.1.0"
description = "Fuzzy Metaballs Differentiable Renderer"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
jupyter = "jupyter lab --ip=0.0.0.0 --no-browser"

[dependencies]
# Python runtime
python = "==3.11.14"

# Core conda packages (exact versions with builds)
_libgcc_mutex = { version = "==0.1", build = "conda_forge" }
_openmp_mutex = { version = "==4.5", build = "2_gnu" }
asttokens = { version = "==3.0.0", build = "pyhd8ed1ab_1" }
bzip2 = { version = "==1.0.8", build = "hda65f42_8" }
ca-certificates = { version = "==2025.10.5", build = "hbd8a1cb_0" }
comm = { version = "==0.2.3", build = "pyhe01879c_0" }
debugpy = { version = "==1.8.17", build = "py311hc665b79_0" }
decorator = { version = "==5.2.1", build = "pyhd8ed1ab_0" }
exceptiongroup = { version = "==1.3.0", build = "pyhd8ed1ab_0" }
executing = { version = "==2.2.1", build = "pyhd8ed1ab_0" }
importlib-metadata = { version = "==8.7.0", build = "pyhe01879c_1" }
ipykernel = { version = "==7.0.1", build = "pyha191276_0" }
ipython = { version = "==9.6.0", build = "pyhfa0c392_0" }
ipython_pygments_lexers = { version = "==1.1.1", build = "pyhd8ed1ab_0" }
jedi = { version = "==0.19.2", build = "pyhd8ed1ab_1" }
jupyter_client = { version = "==8.6.3", build = "pyhd8ed1ab_1" }
jupyter_core = { version = "==5.9.1", build = "pyhc90fa1f_0" }
keyutils = { version = "==1.6.3", build = "hb9d3cd8_0" }
krb5 = { version = "==1.21.3", build = "h659f571_0" }
ld_impl_linux-64 = { version = "==2.44", build = "ha97dd6f_2" }
libedit = { version = "==3.1.20250104", build = "pl5321h7949ede_0" }
libexpat = { version = "==2.7.1", build = "hecca717_0" }
libffi = { version = "==3.5.2", build = "h9ec8514_0" }
libgcc = { version = "==15.2.0", build = "h767d61c_7" }
libgcc-ng = { version = "==15.2.0", build = "h69a702a_7" }
libgomp = { version = "==15.2.0", build = "h767d61c_7" }
liblzma = { version = "==5.8.1", build = "hb9d3cd8_2" }
libnsl = { version = "==2.0.1", build = "hb9d3cd8_1" }
libsodium = { version = "==1.0.20", build = "h4ab18f5_0" }
libsqlite = { version = "==3.50.4", build = "h0c1763c_0" }
libstdcxx = { version = "==15.2.0", build = "h8f9b012_7" }
libstdcxx-ng = { version = "==15.2.0", build = "h4852527_7" }
libuuid = { version = "==2.41.2", build = "he9a06e4_0" }
libxcrypt = { version = "==4.4.36", build = "hd590300_1" }
libzlib = { version = "==1.3.1", build = "hb9d3cd8_2" }
matplotlib-inline = { version = "==0.1.7", build = "pyhd8ed1ab_1" }
ncurses = { version = "==6.5", build = "h2d0b736_3" }
nest-asyncio = { version = "==1.6.0", build = "pyhd8ed1ab_1" }
openssl = { version = "==3.5.4", build = "h26f9b46_0" }
packaging = { version = "==25.0", build = "pyh29332c3_1" }
parso = { version = "==0.8.5", build = "pyhcf101f3_0" }
pexpect = { version = "==4.9.0", build = "pyhd8ed1ab_1" }
pickleshare = { version = "==0.7.5", build = "pyhd8ed1ab_1004" }
pip = { version = "==25.2", build = "pyh8b19718_0" }
platformdirs = { version = "==4.5.0", build = "pyhcf101f3_0" }
prompt-toolkit = { version = "==3.0.52", build = "pyha770c72_0" }
psutil = { version = "==7.1.1", build = "py311h49ec1c0_0" }
ptyprocess = { version = "==0.7.0", build = "pyhd8ed1ab_1" }
pure_eval = { version = "==0.2.3", build = "pyhd8ed1ab_1" }
pygments = { version = "==2.19.2", build = "pyhd8ed1ab_0" }
python-dateutil = { version = "==2.9.0.post0", build = "pyhe01879c_2" }
python_abi = { version = "==3.11", build = "8_cp311" }
pyzmq = { version = "==27.1.0", build = "py311h2315fbb_0" }
readline = { version = "==8.2", build = "h8c095d6_2" }
setuptools = { version = "==80.9.0", build = "pyhff2d567_0" }
six = { version = "==1.17.0", build = "pyhe01879c_1" }
stack_data = { version = "==0.6.3", build = "pyhd8ed1ab_1" }
tk = { version = "==8.6.13", build = "noxft_hd72426e_102" }
tornado = { version = "==6.5.2", build = "py311h49ec1c0_1" }
traitlets = { version = "==5.14.3", build = "pyhd8ed1ab_1" }
typing_extensions = { version = "==4.15.0", build = "pyhcf101f3_0" }
tzdata = { version = "==2025b", build = "h78e105d_0" }
wcwidth = { version = "==0.2.14", build = "pyhd8ed1ab_0" }
wheel = { version = "==0.45.1", build = "pyhd8ed1ab_1" }
zeromq = { version = "==4.3.5", build = "h387f397_9" }
zipp = { version = "==3.23.0", build = "pyhd8ed1ab_0" }

# Jupyter packages
jupyterlab = "*"
notebook = "*"

# PyPI packages (exact versions)
[pypi-dependencies]
absl-py = "==2.3.1"
chex = "==0.1.91"
contourpy = "==1.3.3"
cycler = "==0.12.1"
filelock = "==3.20.0"
fonttools = "==4.60.1"
freetype-py = "==2.5.1"
fsspec = "==2025.9.0"
imageio = "==2.37.0"
ipywidgets = "==8.1.7"
jax = { version = "==0.8.0", extras = ["cuda12"] }
jaxlib = "==0.8.0"
jinja2 = "==3.1.6"
jupyterlab-widgets = "==3.0.15"
kiwisolver = "==1.4.9"
lazy-loader = "==0.4"
markupsafe = "==3.0.3"
matplotlib = "==3.10.7"
ml-dtypes = "==0.5.3"
mpmath = "==1.3.0"
networkx = "==3.5"
numpy = "==2.3.4"
opt-einsum = "==3.4.0"
optax = "==0.2.6"
pillow = "==12.0.0"
pyglet = "==2.1.9"
pyopengl = "==3.1.0"
pyparsing = "==3.2.5"
pyrender = "==0.1.45"
pyvirtualdisplay = "==3.0"
scikit-image = "==0.25.2"
scipy = "==1.16.2"
sympy = "==1.14.0"
tifffile = "==2025.10.16"
toolz = "==1.1.0"
tqdm = "==4.67.1"
transforms3d = "==0.4.2"
trimesh = "==4.9.0"
widgetsnbextension = "==4.0.14"
