hyperparams:
  beta2_exp: 0.5881105287258233
  beta3_exp: 0.10630094869137875
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    3OYqYakUE0A=
  num_mixtures: 123
  rand_sphere_size: 24.917510725674774
optimization:
  batch_size: 1885
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    8Uw16gAYeD8=
  lr_decay_max_drops: 27
  lr_decay_p_thresh: 0.3992736105370901
  lr_decay_p_window: 7
  lr_decay_slope_less: -0.0007781471323244932
  lr_decay_window: 47
  num_epochs: 62
  opt_shape_scale: 4.722763353235583
random_seed: 42
rendering:
  image_height: 130
  image_width: 107
  num_views: 16
  vfov_degrees: 28.665081128193194
