hyperparams:
  beta2_exp: 3.032836139004828
  beta3_exp: 0.14584669414838883
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    yNlWAmnd+T8=
  num_mixtures: 31
  rand_sphere_size: 85.50908297712184
optimization:
  batch_size: 2775
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AR4w7NFJbD8=
  lr_decay_max_drops: 22
  lr_decay_p_thresh: 0.2494920654677454
  lr_decay_p_window: 12
  lr_decay_slope_less: -0.008169910110005394
  lr_decay_window: 11
  num_epochs: 80
  opt_shape_scale: 3.9159407170354648
random_seed: 42
rendering:
  image_height: 203
  image_width: 40
  num_views: 45
  vfov_degrees: 32.038643441360776
