hyperparams:
  beta2_exp: 2.8059011981173483
  beta3_exp: 0.6629514467495078
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    j58VyarsyD8=
  num_mixtures: 119
  rand_sphere_size: 14.78472817913393
optimization:
  batch_size: 1799
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    3SEL1KrMoT8=
  lr_decay_max_drops: 15
  lr_decay_p_thresh: 0.4298730384494115
  lr_decay_p_window: 15
  lr_decay_slope_less: -0.00972492529140867
  lr_decay_window: 17
  num_epochs: 37
  opt_shape_scale: 2.0873983218491583
random_seed: 42
rendering:
  image_height: 180
  image_width: 118
  num_views: 28
  vfov_degrees: 48.71752265605594
