hyperparams:
  beta2_exp: 2.560065007215681
  beta3_exp: 0.9458076077506327
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    +kJNd2jEwT8=
  num_mixtures: 104
  rand_sphere_size: 20.695421523113698
optimization:
  batch_size: 809
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    qafEr9vitD8=
  lr_decay_max_drops: 10
  lr_decay_p_thresh: 0.47491392590780024
  lr_decay_p_window: 20
  lr_decay_slope_less: -0.0057723338074824665
  lr_decay_window: 28
  num_epochs: 19
  opt_shape_scale: 0.9357956723274565
random_seed: 42
rendering:
  image_height: 57
  image_width: 250
  num_views: 46
  vfov_degrees: 55.54147661042373
