hyperparams:
  beta2_exp: 4.442846354786317
  beta3_exp: 0.8084238731259934
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    bnR2abDq4j8=
  num_mixtures: 36
  rand_sphere_size: 171.91383738279464
optimization:
  batch_size: 3825
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    g3ZDDEpfcz8=
  lr_decay_max_drops: 15
  lr_decay_p_thresh: 0.5193219561119523
  lr_decay_p_window: 15
  lr_decay_slope_less: -0.009972340778629473
  lr_decay_window: 49
  num_epochs: 40
  opt_shape_scale: 0.8189873560108348
random_seed: 42
rendering:
  image_height: 36
  image_width: 164
  num_views: 49
  vfov_degrees: 55.04516413432232
