hyperparams:
  beta2_exp: 4.802003642364003
  beta3_exp: 0.8553909415409663
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    Eh3UDHrw5j8=
  num_mixtures: 79
  rand_sphere_size: 8.563799597439646
optimization:
  batch_size: 3277
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    2j/eLCg43T8=
  lr_decay_max_drops: 3
  lr_decay_p_thresh: 0.31200481909895994
  lr_decay_p_window: 3
  lr_decay_slope_less: -0.004601172900280519
  lr_decay_window: 33
  num_epochs: 39
  opt_shape_scale: 1.6249517448486568
random_seed: 42
rendering:
  image_height: 62
  image_width: 247
  num_views: 33
  vfov_degrees: 21.56762563548198
