hyperparams:
  beta2_exp: 3.5272226685701122
  beta3_exp: 0.08827011168693881
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    WJE1b8yYwD8=
  num_mixtures: 35
  rand_sphere_size: 67.7409287368471
optimization:
  batch_size: 1077
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    gMmMcWtv7j8=
  lr_decay_max_drops: 28
  lr_decay_p_thresh: 0.7226245518201898
  lr_decay_p_window: 9
  lr_decay_slope_less: -0.008539888809357226
  lr_decay_window: 39
  num_epochs: 43
  opt_shape_scale: 1.7381923898584073
random_seed: 42
rendering:
  image_height: 150
  image_width: 66
  num_views: 18
  vfov_degrees: 59.18510076875833
