hyperparams:
  beta2_exp: 1.7695135208648336
  beta3_exp: 0.6400246060520989
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    lEdxxthy4z8=
  num_mixtures: 191
  rand_sphere_size: 144.72582236066228
optimization:
  batch_size: 3183
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    uIritSrr3z8=
  lr_decay_max_drops: 28
  lr_decay_p_thresh: 0.2534827241700486
  lr_decay_p_window: 13
  lr_decay_slope_less: -0.00012247439536089942
  lr_decay_window: 27
  num_epochs: 83
  opt_shape_scale: 0.9929940632561414
random_seed: 42
rendering:
  image_height: 96
  image_width: 135
  num_views: 41
  vfov_degrees: 69.05586605977997
