hyperparams:
  beta2_exp: 0.7723864748315712
  beta3_exp: 0.19146720580671112
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    ELN7x2mX+T8=
  num_mixtures: 138
  rand_sphere_size: 195.36480377604425
optimization:
  batch_size: 1458
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    mEIF8kJjpT8=
  lr_decay_max_drops: 14
  lr_decay_p_thresh: 0.38197919992820417
  lr_decay_p_window: 17
  lr_decay_slope_less: -0.00032807199499194223
  lr_decay_window: 11
  num_epochs: 84
  opt_shape_scale: 1.9349925348876726
random_seed: 42
rendering:
  image_height: 214
  image_width: 194
  num_views: 26
  vfov_degrees: 73.56299762469845
