hyperparams:
  beta2_exp: 1.7694109883692342
  beta3_exp: 0.4862849275406571
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    TP2LO14Awz8=
  num_mixtures: 97
  rand_sphere_size: 119.122968233354
optimization:
  batch_size: 1739
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    sCeVDjMUjz8=
  lr_decay_max_drops: 21
  lr_decay_p_thresh: 0.6553582884430655
  lr_decay_p_window: 6
  lr_decay_slope_less: -0.0002413108628622103
  lr_decay_window: 25
  num_epochs: 36
  opt_shape_scale: 1.3941448221566548
random_seed: 42
rendering:
  image_height: 165
  image_width: 58
  num_views: 43
  vfov_degrees: 40.735925813992104
