hyperparams:
  beta2_exp: 3.2216183382003285
  beta3_exp: 0.8442701465378871
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    +TBHnl3L8T8=
  num_mixtures: 83
  rand_sphere_size: 68.38541563057012
optimization:
  batch_size: 527
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Hhwt+Js9WT8=
  lr_decay_max_drops: 19
  lr_decay_p_thresh: 0.6138430945776456
  lr_decay_p_window: 8
  lr_decay_slope_less: -0.008344282287021982
  lr_decay_window: 43
  num_epochs: 20
  opt_shape_scale: 1.4603974822225287
random_seed: 42
rendering:
  image_height: 94
  image_width: 140
  num_views: 43
  vfov_degrees: 55.87920040711297
