hyperparams:
  beta2_exp: 2.72502104963749
  beta3_exp: 0.29569379677027824
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    Bn9VIQN60j8=
  num_mixtures: 86
  rand_sphere_size: 94.96789483725722
optimization:
  batch_size: 1283
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    XDlA61Fb9z8=
  lr_decay_max_drops: 27
  lr_decay_p_thresh: 0.8731488719691144
  lr_decay_p_window: 4
  lr_decay_slope_less: -0.0014716210743489985
  lr_decay_window: 25
  num_epochs: 49
  opt_shape_scale: 2.3762231983616577
random_seed: 42
rendering:
  image_height: 90
  image_width: 44
  num_views: 41
  vfov_degrees: 40.45141224862567
