hyperparams:
  beta2_exp: 1.890137757104378
  beta3_exp: 0.5584220128850782
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    lbvcoykLHEA=
  num_mixtures: 84
  rand_sphere_size: 150.72928821786448
optimization:
  batch_size: 1151
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    o9NEqC0oaT8=
  lr_decay_max_drops: 25
  lr_decay_p_thresh: 0.5436879650065268
  lr_decay_p_window: 14
  lr_decay_slope_less: -0.009745325456490527
  lr_decay_window: 18
  num_epochs: 86
  opt_shape_scale: 1.0395870614419458
random_seed: 42
rendering:
  image_height: 40
  image_width: 50
  num_views: 32
  vfov_degrees: 65.58588631858919
