hyperparams:
  beta2_exp: 3.3678858926801745
  beta3_exp: 0.3800730510884381
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    XNxAv9jbCkA=
  num_mixtures: 122
  rand_sphere_size: 19.385260126117082
optimization:
  batch_size: 3662
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    OWWgv4AZyT8=
  lr_decay_max_drops: 13
  lr_decay_p_thresh: 0.7378548395313359
  lr_decay_p_window: 12
  lr_decay_slope_less: -0.004923112095669162
  lr_decay_window: 34
  num_epochs: 62
  opt_shape_scale: 2.7419283790085673
random_seed: 42
rendering:
  image_height: 116
  image_width: 205
  num_views: 39
  vfov_degrees: 21.190078844081654
