hyperparams:
  beta2_exp: 2.9599496935466765
  beta3_exp: 0.3778975297403011
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    tffBlcsx7z8=
  num_mixtures: 136
  rand_sphere_size: 169.69579357304337
optimization:
  batch_size: 3347
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    k4tn6qU4xz8=
  lr_decay_max_drops: 18
  lr_decay_p_thresh: 0.34540835659484614
  lr_decay_p_window: 16
  lr_decay_slope_less: -0.009208676842610855
  lr_decay_window: 49
  num_epochs: 61
  opt_shape_scale: 0.8702892818257207
random_seed: 42
rendering:
  image_height: 48
  image_width: 116
  num_views: 48
  vfov_degrees: 59.77689861894002
