hyperparams:
  beta2_exp: 3.532966798667434
  beta3_exp: 0.3469596840793792
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    8HK2XZ7E9T8=
  num_mixtures: 111
  rand_sphere_size: 164.2519557687578
optimization:
  batch_size: 1358
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    QnUQYhy6tT8=
  lr_decay_max_drops: 8
  lr_decay_p_thresh: 0.42934555390622575
  lr_decay_p_window: 7
  lr_decay_slope_less: -0.00467108722556718
  lr_decay_window: 8
  num_epochs: 66
  opt_shape_scale: 0.8617273751948055
random_seed: 42
rendering:
  image_height: 99
  image_width: 210
  num_views: 9
  vfov_degrees: 30.667459895110653
