hyperparams:
  beta2_exp: 1.6379074398956182
  beta3_exp: 0.04750787885905605
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    cRpXglp94D8=
  num_mixtures: 55
  rand_sphere_size: 61.46024962049812
optimization:
  batch_size: 3677
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    I6KmSUiXaT8=
  lr_decay_max_drops: 11
  lr_decay_p_thresh: 0.49967591699888947
  lr_decay_p_window: 20
  lr_decay_slope_less: -0.006401023556716808
  lr_decay_window: 33
  num_epochs: 33
  opt_shape_scale: 1.2625638970152162
random_seed: 42
rendering:
  image_height: 199
  image_width: 83
  num_views: 16
  vfov_degrees: 25.27013243930663
