hyperparams:
  beta2_exp: 3.0164299952428957
  beta3_exp: 0.07487556107804004
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    sCU8+fn60z8=
  num_mixtures: 186
  rand_sphere_size: 20.43671204864882
optimization:
  batch_size: 2193
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    5EYTyiV1aD8=
  lr_decay_max_drops: 19
  lr_decay_p_thresh: 0.34363896489677065
  lr_decay_p_window: 15
  lr_decay_slope_less: -0.005810230486198589
  lr_decay_window: 13
  num_epochs: 85
  opt_shape_scale: 1.5977285909254342
random_seed: 42
rendering:
  image_height: 183
  image_width: 101
  num_views: 31
  vfov_degrees: 31.248705225874396
