hyperparams:
  beta2_exp: 3.45463274603514
  beta3_exp: 0.5475661521031864
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    zAw1Qimq5T8=
  num_mixtures: 158
  rand_sphere_size: 5.076790219689047
optimization:
  batch_size: 829
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    nTPNt+cAsz8=
  lr_decay_max_drops: 17
  lr_decay_p_thresh: 0.6175770362735321
  lr_decay_p_window: 6
  lr_decay_slope_less: -0.0037939277486156078
  lr_decay_window: 34
  num_epochs: 32
  opt_shape_scale: 2.6137405035595815
random_seed: 42
rendering:
  image_height: 83
  image_width: 120
  num_views: 11
  vfov_degrees: 70.09232381546298
