hyperparams:
  beta2_exp: 2.702320121925308
  beta3_exp: 0.7652118363082796
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    k3blc3sDI0A=
  num_mixtures: 39
  rand_sphere_size: 59.056002949304016
optimization:
  batch_size: 1295
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    9msXGow5vT8=
  lr_decay_max_drops: 19
  lr_decay_p_thresh: 0.7134149672657045
  lr_decay_p_window: 4
  lr_decay_slope_less: -0.003136634012763875
  lr_decay_window: 13
  num_epochs: 78
  opt_shape_scale: 3.1988256404842357
random_seed: 42
rendering:
  image_height: 116
  image_width: 181
  num_views: 32
  vfov_degrees: 55.177124001197384
