hyperparams:
  beta2_exp: 1.9750620620679795
  beta3_exp: 0.9817674257774937
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    8sf1mnia5z8=
  num_mixtures: 17
  rand_sphere_size: 185.10484167120725
optimization:
  batch_size: 539
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    jqIEzxNO4T8=
  lr_decay_max_drops: 24
  lr_decay_p_thresh: 0.7232074324133227
  lr_decay_p_window: 19
  lr_decay_slope_less: -0.0034553991118683753
  lr_decay_window: 34
  num_epochs: 69
  opt_shape_scale: 3.2357584403873934
random_seed: 42
rendering:
  image_height: 73
  image_width: 123
  num_views: 27
  vfov_degrees: 74.72449022270864
