hyperparams:
  beta2_exp: 2.4405534010845686
  beta3_exp: 0.2872780039807706
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    oLgq+iKR4j8=
  num_mixtures: 67
  rand_sphere_size: 191.0869426238825
optimization:
  batch_size: 944
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    GTK5PSSHgj8=
  lr_decay_max_drops: 7
  lr_decay_p_thresh: 0.313347501320253
  lr_decay_p_window: 14
  lr_decay_slope_less: -0.00010703270968414301
  lr_decay_window: 50
  num_epochs: 47
  opt_shape_scale: 4.276921624307808
random_seed: 42
rendering:
  image_height: 216
  image_width: 39
  num_views: 42
  vfov_degrees: 73.66527397049512
