hyperparams:
  beta2_exp: 3.9953829544155015
  beta3_exp: 0.6053578466922461
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    Et0wJGW5zD8=
  num_mixtures: 111
  rand_sphere_size: 132.09370639850658
optimization:
  batch_size: 3836
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    aS+EVs4d4j8=
  lr_decay_max_drops: 17
  lr_decay_p_thresh: 0.38248921364511623
  lr_decay_p_window: 18
  lr_decay_slope_less: -0.0035694974129521105
  lr_decay_window: 16
  num_epochs: 56
  opt_shape_scale: 2.890098731168424
random_seed: 42
rendering:
  image_height: 92
  image_width: 202
  num_views: 29
  vfov_degrees: 62.17628130602297
