hyperparams:
  beta2_exp: 4.084785944031147
  beta3_exp: 0.04047942303685549
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    Jl2CPc6G9T8=
  num_mixtures: 55
  rand_sphere_size: 189.2118710100099
optimization:
  batch_size: 1669
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    roHsqGQB3D8=
  lr_decay_max_drops: 11
  lr_decay_p_thresh: 0.5775433521695582
  lr_decay_p_window: 12
  lr_decay_slope_less: -0.0025253010731438015
  lr_decay_window: 6
  num_epochs: 99
  opt_shape_scale: 0.6737365278845384
random_seed: 42
rendering:
  image_height: 221
  image_width: 117
  num_views: 18
  vfov_degrees: 32.343140117574784
