hyperparams:
  beta2_exp: 3.294768413693902
  beta3_exp: 0.9512899974698926
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    p6TytvnG9T8=
  num_mixtures: 81
  rand_sphere_size: 150.69784168061335
optimization:
  batch_size: 2591
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    DR5mTZubZT8=
  lr_decay_max_drops: 18
  lr_decay_p_thresh: 0.7811287199544908
  lr_decay_p_window: 9
  lr_decay_slope_less: -0.0038125112347111986
  lr_decay_window: 40
  num_epochs: 17
  opt_shape_scale: 2.790942026027152
random_seed: 42
rendering:
  image_height: 54
  image_width: 178
  num_views: 17
  vfov_degrees: 68.36752047493513
