hyperparams:
  beta2_exp: 4.223048742260439
  beta3_exp: 0.37351103239068295
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    Z2vdiNQ2CUA=
  num_mixtures: 159
  rand_sphere_size: 147.3587860281027
optimization:
  batch_size: 2541
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    EWonxrNBxT8=
  lr_decay_max_drops: 12
  lr_decay_p_thresh: 0.7559502405011206
  lr_decay_p_window: 20
  lr_decay_slope_less: -0.009258277128181912
  lr_decay_window: 25
  num_epochs: 71
  opt_shape_scale: 2.5481335623099035
random_seed: 42
rendering:
  image_height: 194
  image_width: 42
  num_views: 28
  vfov_degrees: 25.383772404831873
