hyperparams:
  beta2_exp: 1.5889522545716974
  beta3_exp: 0.9182227076665012
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    tUnHDUXG+z8=
  num_mixtures: 14
  rand_sphere_size: 156.93196334760518
optimization:
  batch_size: 2876
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    l0Sjn7gmjD8=
  lr_decay_max_drops: 14
  lr_decay_p_thresh: 0.8698593135926662
  lr_decay_p_window: 13
  lr_decay_slope_less: -0.00742583831725173
  lr_decay_window: 9
  num_epochs: 60
  opt_shape_scale: 3.706819704921189
random_seed: 42
rendering:
  image_height: 218
  image_width: 170
  num_views: 21
  vfov_degrees: 22.26717239387539
