hyperparams:
  beta2_exp: 3.3216329577920356
  beta3_exp: 0.22645430028195931
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    RbEnzSxdEUA=
  num_mixtures: 12
  rand_sphere_size: 162.0914125146043
optimization:
  batch_size: 2073
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    T+aadAMnoj8=
  lr_decay_max_drops: 13
  lr_decay_p_thresh: 0.38147589245142377
  lr_decay_p_window: 20
  lr_decay_slope_less: -0.008075765028595744
  lr_decay_window: 33
  num_epochs: 33
  opt_shape_scale: 2.2422281027270934
random_seed: 42
rendering:
  image_height: 147
  image_width: 103
  num_views: 8
  vfov_degrees: 22.936519557050246
