hyperparams:
  beta2_exp: 1.9794938205325034
  beta3_exp: 0.5266840995624104
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    GlZt+bJ4GkA=
  num_mixtures: 77
  rand_sphere_size: 7.330746768066893
optimization:
  batch_size: 2963
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    jb2L7iDwvz8=
  lr_decay_max_drops: 27
  lr_decay_p_thresh: 0.4330958595907495
  lr_decay_p_window: 20
  lr_decay_slope_less: -0.004032243835057939
  lr_decay_window: 32
  num_epochs: 30
  opt_shape_scale: 3.4704260053588927
random_seed: 42
rendering:
  image_height: 239
  image_width: 232
  num_views: 44
  vfov_degrees: 34.444023131802275
