hyperparams:
  beta2_exp: 2.5887734494297066
  beta3_exp: 0.7842114475985933
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    unwK6Wz7H0A=
  num_mixtures: 99
  rand_sphere_size: 180.06412370185313
optimization:
  batch_size: 3792
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    26CsWHijkD8=
  lr_decay_max_drops: 26
  lr_decay_p_thresh: 0.30288551119250684
  lr_decay_p_window: 11
  lr_decay_slope_less: -0.0028796097508654132
  lr_decay_window: 39
  num_epochs: 55
  opt_shape_scale: 2.129306252796413
random_seed: 42
rendering:
  image_height: 228
  image_width: 214
  num_views: 49
  vfov_degrees: 74.14403262501014
