hyperparams:
  beta2_exp: 0.6733926386510665
  beta3_exp: 0.9087436309773234
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    WCI6blMRwD8=
  num_mixtures: 179
  rand_sphere_size: 110.40124723170881
optimization:
  batch_size: 3913
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    QW7CdkWM4z8=
  lr_decay_max_drops: 20
  lr_decay_p_thresh: 0.7355788323168696
  lr_decay_p_window: 20
  lr_decay_slope_less: -0.004454679442148143
  lr_decay_window: 7
  num_epochs: 4
  opt_shape_scale: 0.8939801723310405
random_seed: 42
rendering:
  image_height: 175
  image_width: 135
  num_views: 18
  vfov_degrees: 30.188040880510453
