hyperparams:
  beta2_exp: 4.349813564347524
  beta3_exp: 0.8230166287840671
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    WoyK4WKuF0A=
  num_mixtures: 115
  rand_sphere_size: 150.26303854613806
optimization:
  batch_size: 1327
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    bbzJWVZS4z8=
  lr_decay_max_drops: 25
  lr_decay_p_thresh: 0.5028987543535648
  lr_decay_p_window: 3
  lr_decay_slope_less: -0.00885452165662535
  lr_decay_window: 48
  num_epochs: 98
  opt_shape_scale: 0.806860221944639
random_seed: 42
rendering:
  image_height: 68
  image_width: 163
  num_views: 16
  vfov_degrees: 20.61802123370041
