hyperparams:
  beta2_exp: 4.774791165933626
  beta3_exp: 0.8991391750005309
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    91BGRlw9wj8=
  num_mixtures: 34
  rand_sphere_size: 173.70987369305658
optimization:
  batch_size: 736
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    /2mnTrCt8j8=
  lr_decay_max_drops: 18
  lr_decay_p_thresh: 0.7238266145770592
  lr_decay_p_window: 14
  lr_decay_slope_less: -0.0038417959083225347
  lr_decay_window: 11
  num_epochs: 18
  opt_shape_scale: 2.969002413972472
random_seed: 42
rendering:
  image_height: 169
  image_width: 33
  num_views: 33
  vfov_degrees: 54.84866841536749
