hyperparams:
  beta2_exp: 2.287910094376049
  beta3_exp: 0.7784948889177374
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    B6M4jf6bIEA=
  num_mixtures: 16
  rand_sphere_size: 100.813281843548
optimization:
  batch_size: 3787
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    4cTggpOyiD8=
  lr_decay_max_drops: 19
  lr_decay_p_thresh: 0.3628622780871166
  lr_decay_p_window: 11
  lr_decay_slope_less: -0.007560055187601676
  lr_decay_window: 11
  num_epochs: 50
  opt_shape_scale: 3.165274563202602
random_seed: 42
rendering:
  image_height: 70
  image_width: 114
  num_views: 45
  vfov_degrees: 66.42887098025234
