hyperparams:
  beta2_exp: 0.9664633486141962
  beta3_exp: 0.16537636373707104
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    90tUFOrsyz8=
  num_mixtures: 122
  rand_sphere_size: 56.55081343113646
optimization:
  batch_size: 2899
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    YeWnCRS5/j8=
  lr_decay_max_drops: 27
  lr_decay_p_thresh: 0.7501360332597103
  lr_decay_p_window: 9
  lr_decay_slope_less: -0.004934390772145169
  lr_decay_window: 19
  num_epochs: 59
  opt_shape_scale: 2.6062437571271007
random_seed: 42
rendering:
  image_height: 212
  image_width: 142
  num_views: 36
  vfov_degrees: 58.89222412700346
