hyperparams:
  beta2_exp: 4.836077616229795
  beta3_exp: 0.14992907181892848
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    6RqfNCnivD8=
  num_mixtures: 152
  rand_sphere_size: 48.08531180559246
optimization:
  batch_size: 641
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    5FUJPR3oaD8=
  lr_decay_max_drops: 7
  lr_decay_p_thresh: 0.11393577858138998
  lr_decay_p_window: 9
  lr_decay_slope_less: -0.0022064936698870134
  lr_decay_window: 49
  num_epochs: 87
  opt_shape_scale: 1.0592828074668779
random_seed: 42
rendering:
  image_height: 62
  image_width: 224
  num_views: 33
  vfov_degrees: 56.85432765921791
