hyperparams:
  beta2_exp: 2.8645683363379515
  beta3_exp: 0.4677412514543893
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    LLTBskV53T8=
  num_mixtures: 17
  rand_sphere_size: 173.8986413279784
optimization:
  batch_size: 1526
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Pwx8mQEs5j8=
  lr_decay_max_drops: 17
  lr_decay_p_thresh: 0.45864896724639403
  lr_decay_p_window: 8
  lr_decay_slope_less: -0.0026549108156845944
  lr_decay_window: 23
  num_epochs: 74
  opt_shape_scale: 2.2507729082829324
random_seed: 42
rendering:
  image_height: 207
  image_width: 87
  num_views: 50
  vfov_degrees: 32.50608678090042
