hyperparams:
  beta2_exp: 4.41301944380604
  beta3_exp: 0.9471235381817652
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    f/wz3CkX4D8=
  num_mixtures: 177
  rand_sphere_size: 120.39260796972984
optimization:
  batch_size: 2600
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    Sm8Ukl87gT8=
  lr_decay_max_drops: 2
  lr_decay_p_thresh: 0.5798116223024377
  lr_decay_p_window: 18
  lr_decay_slope_less: -0.002245720657669356
  lr_decay_window: 26
  num_epochs: 53
  opt_shape_scale: 1.276491068655662
random_seed: 42
rendering:
  image_height: 38
  image_width: 230
  num_views: 37
  vfov_degrees: 33.624791678959475
