hyperparams:
  beta2_exp: 4.985033172660563
  beta3_exp: 0.6501994755871353
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    y0G+1tW7+z8=
  num_mixtures: 178
  rand_sphere_size: 92.88104040147756
optimization:
  batch_size: 1320
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    F5+L04WsmT8=
  lr_decay_max_drops: 27
  lr_decay_p_thresh: 0.6201261306429885
  lr_decay_p_window: 20
  lr_decay_slope_less: -0.004255583545373067
  lr_decay_window: 50
  num_epochs: 11
  opt_shape_scale: 0.652206527818795
random_seed: 42
rendering:
  image_height: 144
  image_width: 194
  num_views: 24
  vfov_degrees: 75.42852096475511
