hyperparams:
  beta2_exp: 0.9096478266956429
  beta3_exp: 0.6915312973986323
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    FYIA+eDQAkA=
  num_mixtures: 42
  rand_sphere_size: 122.26312950530881
optimization:
  batch_size: 265
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    yudp9abrcj8=
  lr_decay_max_drops: 5
  lr_decay_p_thresh: 0.3134004983818214
  lr_decay_p_window: 5
  lr_decay_slope_less: -0.005768341427472149
  lr_decay_window: 5
  num_epochs: 53
  opt_shape_scale: 1.5756373932848426
random_seed: 42
rendering:
  image_height: 136
  image_width: 70
  num_views: 8
  vfov_degrees: 28.954471154232902
