hyperparams:
  beta2_exp: 1.4143509547641036
  beta3_exp: 0.5460359098288845
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    jpPcbE2xI0A=
  num_mixtures: 63
  rand_sphere_size: 59.20574836946929
optimization:
  batch_size: 3845
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    RVDKCzL6oj8=
  lr_decay_max_drops: 2
  lr_decay_p_thresh: 0.6944581213108515
  lr_decay_p_window: 5
  lr_decay_slope_less: -0.0026324647781149355
  lr_decay_window: 10
  num_epochs: 78
  opt_shape_scale: 2.711431325835874
random_seed: 42
rendering:
  image_height: 244
  image_width: 176
  num_views: 13
  vfov_degrees: 71.74549431760758
