hyperparams:
  beta2_exp: 1.274238131019452
  beta3_exp: 0.20531290224608736
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    vjlDYR0X2T8=
  num_mixtures: 10
  rand_sphere_size: 130.68220377675593
optimization:
  batch_size: 1937
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    8HY9Nb1icT8=
  lr_decay_max_drops: 9
  lr_decay_p_thresh: 0.47127286635435506
  lr_decay_p_window: 14
  lr_decay_slope_less: -0.005541878587620704
  lr_decay_window: 37
  num_epochs: 89
  opt_shape_scale: 4.615757945433536
random_seed: 42
rendering:
  image_height: 92
  image_width: 154
  num_views: 14
  vfov_degrees: 53.04459050530702
