hyperparams:
  beta2_exp: 2.6951028027030963
  beta3_exp: 0.9325368061727696
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    s2PEoJck3j8=
  num_mixtures: 35
  rand_sphere_size: 117.07661344485157
optimization:
  batch_size: 779
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    CAofEvFSiz8=
  lr_decay_max_drops: 27
  lr_decay_p_thresh: 0.7261371699426618
  lr_decay_p_window: 17
  lr_decay_slope_less: -0.003978153529966323
  lr_decay_window: 50
  num_epochs: 45
  opt_shape_scale: 1.4008591165694098
random_seed: 42
rendering:
  image_height: 129
  image_width: 104
  num_views: 37
  vfov_degrees: 29.93374180624387
