hyperparams:
  beta2_exp: 2.4398859192856515
  beta3_exp: 0.10785493907852854
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    tIAbqrD6D0A=
  num_mixtures: 22
  rand_sphere_size: 37.570072455269546
optimization:
  batch_size: 3550
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    OIvCxIM8tD8=
  lr_decay_max_drops: 20
  lr_decay_p_thresh: 0.45945023111045424
  lr_decay_p_window: 7
  lr_decay_slope_less: -0.0075467450024637225
  lr_decay_window: 19
  num_epochs: 37
  opt_shape_scale: 0.5150288145759906
random_seed: 42
rendering:
  image_height: 187
  image_width: 172
  num_views: 39
  vfov_degrees: 57.381637079881244
