hyperparams:
  beta2_exp: 1.0418437856173122
  beta3_exp: 0.8590838637987891
io:
  mesh_file: data/cow.obj
  model_filename: fuzzy_cow_shape.pkl
  output_dir: output
  save_model: true
model:
  gmm_init_scale: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    a6HW2ItNF0A=
  num_mixtures: 69
  rand_sphere_size: 179.42308192154675
optimization:
  batch_size: 1980
  clip_alpha: 3.0e-08
  initial_lr: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    CIWjECl6cj8=
  lr_decay_max_drops: 11
  lr_decay_p_thresh: 0.14881479273498155
  lr_decay_p_window: 11
  lr_decay_slope_less: -0.0034262244071521326
  lr_decay_window: 9
  num_epochs: 93
  opt_shape_scale: 1.84039001521746
random_seed: 42
rendering:
  image_height: 68
  image_width: 183
  num_views: 14
  vfov_degrees: 56.54236811525484
